version: '3.8'

services:
  front:
    build: ./front
    container_name: client_frontend
    depends_on:
      - postgres
      - redis
      - prometheus
      - grafana
    environment:
      - PORT=3003
    ports:
      - '3003:3003'
    volumes:
      - ./front:/app
      - ./app/node_modules

  postgres:
    image: postgres:16.1-bullseye
    restart: always
    container_name: news_web_app
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=qwerty
     - POSTGRES_DB=go_news
    ports:
     - "5432:5432"
  
  redis:
    image: redis:7.2.3-bookworm 
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - "9090:9090"
    volumes:
      - ./back/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: