version: "3"

tasks:
  dup:
    desc: "Up docker-compose"
    cmds:
      - docker-compose up --build front

  mup:
    desc: "Run migrator action up"
    dir: "./back"
    cmds:
      - go run ./migrations/migrator/migrator.go --action=up

  down:
    desc: "Run migrator action down"
    dir: "./back"
    cmds:
      - go run ./migrations/migrator/migrator.go --action=down

  run_front:
    desc: "Run frontend"
    dir: "./front"
    cmds:
      - PORT=3003 npm start

  run_auth:
    desc: "Run auth service"
    dir: "./back"
    cmds:
      - go run ./app/authService/cmd/auth_service/main.go

  run_news:
    desc: "Run news service"
    dir: "./back"
    cmds:
      - go run ./app/newsService/cmd/news_service/main.go

  run_api:
    desc: "Run api service"
    dir: "./back"
    cmds:
      - go run ./app/apiService/cmd/api_service/main.go

  app_run:
    desc: "Run app"
    deps:
      - dup
      - mup
      - run_auth
      - run_news
      - run_api