version: "3"

tasks:
  run_auth:
    desc: "Run auth service"
    cmds:
      - go run ./app/authService/cmd/auth_service/main.go

  run_news:
    desc: "Run news service"
    cmds:
      - go run ./app/newsService/cmd/news_service/main.go

  run_web:
    desc: "Run web service"
    cmds:
      - go run ./app/webService/cmd/web_service/main.go

  dup:
    desc: "Up docker-compose"
    cmds:
      - docker-compose up -d

  mup:
    desc: "Run migrator action up"
    cmds:
      - go run ./migrations/migrator/migrator.go --action=up

  mdown:
    desc: "Run migrator action down"
    cmds:
      - go run ./migrations/migrator/migrator.go --action=down