# levels of logging: "local"; "local_info"; "dev"; "prod"
env: "local"

news_managment:
  filter_keywords: ["golang", "go", "go*"] # filter for articles
  fetch_interval: 600m # updating new items from rss sources
  refresh_interval: 15m # publication newest article on home page
  articles_limit: 10

api_server:
  address: "0.0.0.0:8008"
  timeout: 4s
  idle_timeout: 60s

grpc_auth:
  host : "authsrv"
  port: 44044
  timeout: 2s

grpc_news:
  host : "newssrv"
  port: 55055
  timeout: 4s

psql_storage:
  db_driver: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "go_news"
  user: "postgres"
  sslmode: "disable"

redis_storage:
  host: "redis"
  port: "6379"

token_managment:
  access_token_ttl: 20m
  refresh_token_ttl: 43200m
