env: "local_info" # "local" | "dev" | "prod"

news_managment:
  filter_keywords: ["golang", "go", "go*"]
  fetch_interval: 30m
  refresh_interval: 15m
  articles_limit: 30

api_server:
  address: "0.0.0.0:8008"
  timeout: 4s
  idle_timeout: 60s

grpc_auth:
  host : "authsrv"
  port: 44044
  timeout: 2s

grpc_news:
  host : "newssrv"
  port: 55055
  timeout: 4s

psql_storage:
  db_driver: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "go_news"
  user: "postgres"
  sslmode: "disable"

redis_storage:
  host: "redis"
  port: "6379"

token_managment:
  access_token_ttl: 20m
  refresh_token_ttl: 43200m
